version: '3'

networks:
  basic:


services:    

  spark-master:
    image: spark
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    hostname: spark-master
    environment:
      MASTER: spark://spark-master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: $PUBLIC_DNS
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./conf/spark-master:/conf
      - ./data:/tmp/data  
    networks:
      - basic
    container_name: spark-master
 
  spark-worker-1:
    image: spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker-1
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: $PUBLIC_DNS
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
    links:
      - spark-master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./conf/spark-worker-1:/conf
      - ./data:/tmp/data
    networks:
      - basic
    container_name: spark-worker-1


  spark-driver:
    image: spark
    command: /bin/bash
    hostname: spark-driver   
    environment:
      SPARK_CONF_DIR: /conf
    tty: true
    ports:
      - 8042:8042
      - 8088:8088
      - 4041:4041
    volumes:      
      - ./conf/spark-driver:/conf
      - ./data:/tmp/data
      - ./scripts:/scripts
    networks:
      - basic
    container_name: spark-driver

